#############################################################################
# Makefile for building: python_module
# Generated by qmake (2.01a) (Qt 4.7.3) on: jeu. août 25 14:15:16 2011
# Project:  python_module.pro
# Template: app
# Command: /Applications/Desktop/Qt/473/gcc/bin/qmake -spec /Applications/Desktop/Qt/473/gcc/mkspecs/macx-g++ -o Makefile python_module.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/Applications/Desktop/Qt/473/gcc/mkspecs/macx-g++ -I. -I/Applications/Desktop/Qt/473/gcc/lib/QtCore.framework/Versions/4/Headers -I/Applications/Desktop/Qt/473/gcc/include/QtCore -I/Applications/Desktop/Qt/473/gcc/include -I/usr/local/include -I/usr/local/include -I. -F/Applications/Desktop/Qt/473/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Applications/Desktop/Qt/473/gcc/lib -L/Applications/Desktop/Qt/473/gcc/lib -L/Users/navaro/Codes/VIC/VIC3D/python_module/../../../../../../usr/local/lib/ -lhdf5 -lfftw3 -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Applications/Desktop/Qt/473/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		xdmf.cpp \
		grid.cpp \
		poisson.cpp \
		tsc.cpp \
		vortexring.cpp 
OBJECTS       = main.o \
		xdmf.o \
		grid.o \
		poisson.o \
		tsc.o \
		vortexring.o
DIST          = /Applications/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/common/mac.conf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		/Applications/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/debug.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf \
		python_module.pro
QMAKE_TARGET  = python_module
DESTDIR       = 
TARGET        = python_module

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): /Users/navaro/Codes/VIC/VIC3D/python_module/../../../../../../usr/local/lib/libhdf5.a /Users/navaro/Codes/VIC/VIC3D/python_module/../../../../../../usr/local/lib/libfftw3.a $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: python_module.pro  /Applications/Desktop/Qt/473/gcc/mkspecs/macx-g++/qmake.conf /Applications/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/common/mac.conf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		/Applications/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/debug.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		/Applications/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /Applications/Desktop/Qt/473/gcc/mkspecs/macx-g++ -o Makefile python_module.pro
/Applications/Desktop/Qt/473/gcc/mkspecs/common/unix.conf:
/Applications/Desktop/Qt/473/gcc/mkspecs/common/mac.conf:
/Applications/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf:
/Applications/Desktop/Qt/473/gcc/mkspecs/qconfig.pri:
/Applications/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/debug.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/qt.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/moc.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/resources.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/uic.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/lex.prf:
/Applications/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /Applications/Desktop/Qt/473/gcc/mkspecs/macx-g++ -o Makefile python_module.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/python_module1.0.0 || $(MKDIR) .tmp/python_module1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/python_module1.0.0/ && $(COPY_FILE) --parents xdmf.hpp grid.hpp poisson.hpp tsc.hpp vortexring.hpp .tmp/python_module1.0.0/ && $(COPY_FILE) --parents main.cpp xdmf.cpp grid.cpp poisson.cpp tsc.cpp vortexring.cpp .tmp/python_module1.0.0/ && (cd `dirname .tmp/python_module1.0.0` && $(TAR) python_module1.0.0.tar python_module1.0.0 && $(COMPRESS) python_module1.0.0.tar) && $(MOVE) `dirname .tmp/python_module1.0.0`/python_module1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/python_module1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp /usr/local/include/hdf5.h \
		/usr/local/include/H5public.h \
		/usr/local/include/H5pubconf.h \
		/usr/local/include/H5version.h \
		/usr/local/include/mpi.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/file_inln.h \
		/usr/local/include/H5api_adpt.h \
		/usr/local/include/H5Apublic.h \
		/usr/local/include/H5Ipublic.h \
		/usr/local/include/H5Opublic.h \
		/usr/local/include/H5Lpublic.h \
		/usr/local/include/H5Tpublic.h \
		/usr/local/include/H5ACpublic.h \
		/usr/local/include/H5Cpublic.h \
		/usr/local/include/H5Dpublic.h \
		/usr/local/include/H5Epublic.h \
		/usr/local/include/H5Epubgen.h \
		/usr/local/include/H5Fpublic.h \
		/usr/local/include/H5FDpublic.h \
		/usr/local/include/H5Gpublic.h \
		/usr/local/include/H5MMpublic.h \
		/usr/local/include/H5Ppublic.h \
		/usr/local/include/H5Zpublic.h \
		/usr/local/include/H5Rpublic.h \
		/usr/local/include/H5Spublic.h \
		/usr/local/include/H5FDcore.h \
		/usr/local/include/H5FDfamily.h \
		/usr/local/include/H5FDlog.h \
		/usr/local/include/H5FDmpi.h \
		/usr/local/include/H5FDmpio.h \
		/usr/local/include/H5FDmpiposix.h \
		/usr/local/include/H5FDmulti.h \
		/usr/local/include/H5FDsec2.h \
		/usr/local/include/H5FDstdio.h \
		/usr/local/include/H5FDdirect.h \
		/usr/local/include/fftw3.h \
		grid.hpp \
		poisson.hpp \
		xdmf.hpp \
		tsc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

xdmf.o: xdmf.cpp xdmf.hpp \
		/usr/local/include/hdf5.h \
		/usr/local/include/H5public.h \
		/usr/local/include/H5pubconf.h \
		/usr/local/include/H5version.h \
		/usr/local/include/mpi.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/file_inln.h \
		/usr/local/include/H5api_adpt.h \
		/usr/local/include/H5Apublic.h \
		/usr/local/include/H5Ipublic.h \
		/usr/local/include/H5Opublic.h \
		/usr/local/include/H5Lpublic.h \
		/usr/local/include/H5Tpublic.h \
		/usr/local/include/H5ACpublic.h \
		/usr/local/include/H5Cpublic.h \
		/usr/local/include/H5Dpublic.h \
		/usr/local/include/H5Epublic.h \
		/usr/local/include/H5Epubgen.h \
		/usr/local/include/H5Fpublic.h \
		/usr/local/include/H5FDpublic.h \
		/usr/local/include/H5Gpublic.h \
		/usr/local/include/H5MMpublic.h \
		/usr/local/include/H5Ppublic.h \
		/usr/local/include/H5Zpublic.h \
		/usr/local/include/H5Rpublic.h \
		/usr/local/include/H5Spublic.h \
		/usr/local/include/H5FDcore.h \
		/usr/local/include/H5FDfamily.h \
		/usr/local/include/H5FDlog.h \
		/usr/local/include/H5FDmpi.h \
		/usr/local/include/H5FDmpio.h \
		/usr/local/include/H5FDmpiposix.h \
		/usr/local/include/H5FDmulti.h \
		/usr/local/include/H5FDsec2.h \
		/usr/local/include/H5FDstdio.h \
		/usr/local/include/H5FDdirect.h \
		grid.hpp \
		poisson.hpp \
		/usr/local/include/fftw3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xdmf.o xdmf.cpp

grid.o: grid.cpp grid.hpp \
		/usr/local/include/hdf5.h \
		/usr/local/include/H5public.h \
		/usr/local/include/H5pubconf.h \
		/usr/local/include/H5version.h \
		/usr/local/include/mpi.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/file_inln.h \
		/usr/local/include/H5api_adpt.h \
		/usr/local/include/H5Apublic.h \
		/usr/local/include/H5Ipublic.h \
		/usr/local/include/H5Opublic.h \
		/usr/local/include/H5Lpublic.h \
		/usr/local/include/H5Tpublic.h \
		/usr/local/include/H5ACpublic.h \
		/usr/local/include/H5Cpublic.h \
		/usr/local/include/H5Dpublic.h \
		/usr/local/include/H5Epublic.h \
		/usr/local/include/H5Epubgen.h \
		/usr/local/include/H5Fpublic.h \
		/usr/local/include/H5FDpublic.h \
		/usr/local/include/H5Gpublic.h \
		/usr/local/include/H5MMpublic.h \
		/usr/local/include/H5Ppublic.h \
		/usr/local/include/H5Zpublic.h \
		/usr/local/include/H5Rpublic.h \
		/usr/local/include/H5Spublic.h \
		/usr/local/include/H5FDcore.h \
		/usr/local/include/H5FDfamily.h \
		/usr/local/include/H5FDlog.h \
		/usr/local/include/H5FDmpi.h \
		/usr/local/include/H5FDmpio.h \
		/usr/local/include/H5FDmpiposix.h \
		/usr/local/include/H5FDmulti.h \
		/usr/local/include/H5FDsec2.h \
		/usr/local/include/H5FDstdio.h \
		/usr/local/include/H5FDdirect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grid.o grid.cpp

poisson.o: poisson.cpp poisson.hpp \
		/usr/local/include/fftw3.h \
		grid.hpp \
		/usr/local/include/hdf5.h \
		/usr/local/include/H5public.h \
		/usr/local/include/H5pubconf.h \
		/usr/local/include/H5version.h \
		/usr/local/include/mpi.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/file_inln.h \
		/usr/local/include/H5api_adpt.h \
		/usr/local/include/H5Apublic.h \
		/usr/local/include/H5Ipublic.h \
		/usr/local/include/H5Opublic.h \
		/usr/local/include/H5Lpublic.h \
		/usr/local/include/H5Tpublic.h \
		/usr/local/include/H5ACpublic.h \
		/usr/local/include/H5Cpublic.h \
		/usr/local/include/H5Dpublic.h \
		/usr/local/include/H5Epublic.h \
		/usr/local/include/H5Epubgen.h \
		/usr/local/include/H5Fpublic.h \
		/usr/local/include/H5FDpublic.h \
		/usr/local/include/H5Gpublic.h \
		/usr/local/include/H5MMpublic.h \
		/usr/local/include/H5Ppublic.h \
		/usr/local/include/H5Zpublic.h \
		/usr/local/include/H5Rpublic.h \
		/usr/local/include/H5Spublic.h \
		/usr/local/include/H5FDcore.h \
		/usr/local/include/H5FDfamily.h \
		/usr/local/include/H5FDlog.h \
		/usr/local/include/H5FDmpi.h \
		/usr/local/include/H5FDmpio.h \
		/usr/local/include/H5FDmpiposix.h \
		/usr/local/include/H5FDmulti.h \
		/usr/local/include/H5FDsec2.h \
		/usr/local/include/H5FDstdio.h \
		/usr/local/include/H5FDdirect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o poisson.o poisson.cpp

tsc.o: tsc.cpp tsc.hpp \
		grid.hpp \
		/usr/local/include/hdf5.h \
		/usr/local/include/H5public.h \
		/usr/local/include/H5pubconf.h \
		/usr/local/include/H5version.h \
		/usr/local/include/mpi.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/include/openmpi/ompi/mpi/cxx/file_inln.h \
		/usr/local/include/H5api_adpt.h \
		/usr/local/include/H5Apublic.h \
		/usr/local/include/H5Ipublic.h \
		/usr/local/include/H5Opublic.h \
		/usr/local/include/H5Lpublic.h \
		/usr/local/include/H5Tpublic.h \
		/usr/local/include/H5ACpublic.h \
		/usr/local/include/H5Cpublic.h \
		/usr/local/include/H5Dpublic.h \
		/usr/local/include/H5Epublic.h \
		/usr/local/include/H5Epubgen.h \
		/usr/local/include/H5Fpublic.h \
		/usr/local/include/H5FDpublic.h \
		/usr/local/include/H5Gpublic.h \
		/usr/local/include/H5MMpublic.h \
		/usr/local/include/H5Ppublic.h \
		/usr/local/include/H5Zpublic.h \
		/usr/local/include/H5Rpublic.h \
		/usr/local/include/H5Spublic.h \
		/usr/local/include/H5FDcore.h \
		/usr/local/include/H5FDfamily.h \
		/usr/local/include/H5FDlog.h \
		/usr/local/include/H5FDmpi.h \
		/usr/local/include/H5FDmpio.h \
		/usr/local/include/H5FDmpiposix.h \
		/usr/local/include/H5FDmulti.h \
		/usr/local/include/H5FDsec2.h \
		/usr/local/include/H5FDstdio.h \
		/usr/local/include/H5FDdirect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tsc.o tsc.cpp

vortexring.o: vortexring.cpp vortexring.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vortexring.o vortexring.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

